"""Additive S5 imaging foundation contracts and extension points."""

from .contracts import (
    DerivativeArtifact,
    DerivativeLineage,
    DerivativePurpose,
    ImageDimensions,
    IntegrityStatus,
    SourceDimensions,
    SourceIdentity,
    SourceMetadata,
    lineage_for_bytes,
    sha256_bytes,
    validate_derivative_lineage,
)
from .registry import (
    DerivativeBuilder,
    DerivativeBuilderRegistry,
    ImageDecodeError,
    ImageHandler,
    ImageHandlerRegistry,
    RasterImageHandler,
    UnsupportedImageHandlerError,
    default_image_handler_registry,
)
from .derivatives import (
    CoordinateMapping,
    DerivativeError,
    DerivativePayloadTooLargeError,
    DerivativeService,
    PreparedDerivative,
    map_lesion_result_to_review,
)

__all__ = [
    "DerivativeArtifact",
    "DerivativeBuilder",
    "DerivativeBuilderRegistry",
    "DerivativeError",
    "DerivativePayloadTooLargeError",
    "DerivativeLineage",
    "DerivativePurpose",
    "DerivativeService",
    "ImageDecodeError",
    "ImageDimensions",
    "ImageHandler",
    "ImageHandlerRegistry",
    "IntegrityStatus",
    "RasterImageHandler",
    "SourceDimensions",
    "SourceIdentity",
    "SourceMetadata",
    "UnsupportedImageHandlerError",
    "CoordinateMapping",
    "PreparedDerivative",
    "default_image_handler_registry",
    "lineage_for_bytes",
    "sha256_bytes",
    "validate_derivative_lineage",
    "map_lesion_result_to_review",
]
