"""Additive S5 imaging foundation contracts and extension points."""

from .contracts import (
    DerivativeArtifact,
    DerivativeLineage,
    DerivativePurpose,
    ImageDimensions,
    IntegrityStatus,
    SourceDimensions,
    SourceAlias,
    SourceChange,
    SourceIntegrity,
    SourceIdentity,
    SourceMetadata,
    lineage_for_bytes,
    sha256_bytes,
    validate_derivative_lineage,
)
from .registry import (
    DerivativeBuilder,
    DerivativeBuilderRegistry,
    ImageDecodeError,
    ImageHandler,
    ImageHandlerRegistry,
    RasterImageHandler,
    UnsupportedImageHandlerError,
    default_image_handler_registry,
)

__all__ = [
    "DerivativeArtifact",
    "DerivativeBuilder",
    "DerivativeBuilderRegistry",
    "DerivativeLineage",
    "DerivativePurpose",
    "ImageDecodeError",
    "ImageDimensions",
    "ImageHandler",
    "ImageHandlerRegistry",
    "IntegrityStatus",
    "RasterImageHandler",
    "SourceDimensions",
    "SourceAlias",
    "SourceChange",
    "SourceIntegrity",
    "SourceIdentity",
    "SourceMetadata",
    "UnsupportedImageHandlerError",
    "default_image_handler_registry",
    "lineage_for_bytes",
    "sha256_bytes",
    "validate_derivative_lineage",
]
