/**
 * Lucide icon barrel.
 *
 * Centralised so feature modules never reach into `lucide-react` directly —
 * this makes swapping the icon set or upgrading later a single-file edit and
 * keeps the audit surface small.
 *
 * All names match the lucide-react export names. Tree-shake friendly: only
 * icons imported here end up in the production bundle.
 *
 * No emoji are used as UI icons anywhere in this codebase.
 */
export {
  Activity,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  BadgeCheck,
  Beaker,
  Bell,
  Calendar,
  Camera,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleDot,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Compass,
  Construction,
  Copy,
  Database,
  Download,
  Eye,
  EyeOff,
  FileImage,
  Filter,
  Flame,
  Folder,
  FolderOpen,
  GitBranch,
  Globe,
  HeartPulse,
  History,
  Image as ImageIcon,
  Info,
  Layers,
  LineChart,
  ListChecks,
  ListTree,
  Loader2,
  Lock,
  LogOut,
  MapPin,
  Maximize2,
  Menu,
  MessageSquare,
  Minus,
  MoreHorizontal,
  PanelLeftClose,
  PanelLeftOpen,
  Pause,
  Pencil,
  Play,
  Plug,
  Plus,
  Radar,
  RefreshCw,
  RotateCcw,
  Save,
  Scale,
  ScanLine,
  Search,
  Settings as Settings2,
  ShieldCheck,
  Sparkles,
  Square,
  Stethoscope,
  Sun,
  Tag,
  Target,
  TestTube2,
  ToggleLeft,
  ToggleRight,
  Trash2,
  TrendingUp,
  Upload,
  User,
  UserRound,
  Users,
  X,
  XCircle,
  ZoomIn,
  ZoomOut,
} from 'lucide-react';

/** Common icon type — `LucideIcon` from lucide-react. Re-exported for convenience. */
export type { LucideIcon } from 'lucide-react';
